spring.application.name=eventease

spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.url=jdbc:mysql://localhost:3306/eventEase
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop