spring.application.name=eventease

spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.url=jdbc:mysql://localhost:3306/eventEase
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Configuración JWT
jwt.secret=mi_clave_super_secreta_para_eventease_2026_con_mas_de_32_caracteres
jwt.expiration=3600000
cors.origin=http://localhost:4200